<?php
function prettyPrint($a)
{
    echo "<pre>";
    print_r($a);
    echo "</pre>";
}

function prettyPrintJson($a)
{
    echo "<pre>";
    $pretty = json_encode($a, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    print_r($pretty);
    echo "</pre>";
}

$urlBase = OntoWiki::getInstance()->getUrlBase();

?>

<script type="text/javascript" src="<?php echo ($urlBase . 'extensions/statements/templates/statements/js/statements.js')?>"></script>
<script type="text/javascript" src="<?php echo ($urlBase . 'extensions/statements/templates/statements/js/handlebars.js')?>"></script>
<script type="text/javascript" src="<?php echo ($urlBase . 'extensions/statements/templates/statements/js/jquery.fancytree-all.min.js')?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo ($urlBase . 'extensions/statements/templates/statements/css/statements.css')?>">
<link rel="stylesheet" type="text/css" href="<?php echo ($urlBase . 'extensions/statements/templates/statements/css/ui.fancytree.css')?>">

<div id="smc-headline">
    <?php echo $this->_('Library'); ?>: <?php echo $this->label; ?>
</div>

<div id="smc-uri">
    &nbsp;(<?php echo $this->membership; ?>)
</div>

<div style="clear: both;">
    <input id="inputFilterSearch" name="search" class="text" type="search" placeholder="Filter...">
    <button id="btnResetSearch" class="minibutton">&times;</button>
</div>

<div id="tree"></div>

